name: Build LaTeX Document

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v7

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ./introduction.tex 
          working_directory: ./reports/introduction/ 

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ./cee492_final_report.tex
          working_directory: ./reports/final/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: intro-pdf
          archive: false
          path: ./reports/introduction/introduction.pdf 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: exploratory-analysis-pdf 
          archive: false
          path: ./reports/report/exploratory.pdf